# Site settings
title: Hanna Edholm
email: "hannaedholm@gmail.com"
description: "Doula och förlossningsfotograf"
url: "https://hannaedholm.se"
# baseurl: "."
facebook_username: "hannaehdolm"
# twitter_username: ""
instagram_username: "hannaedholm.se"
github_username:  "yarcod/hannaedholm.se"
# deviantart_username: ""
# flickr_username: ""
# discus_shortname: ""
share: true

# Owner/author information
owner:
  name: Hanna Edholm
  avatar: avatar.png
  favicon: favicon.ico
  info: Doula, förlossningsfotograf

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : false
  disqus :
    short_name : ""

# Collections
collections:
  galleries:
    output: true
    permalink: /:collection/:name
# https://stackoverflow.com/a/33488449
# Internal nav
nav:
  - Portfolio: "galleries"
  - Doula: "information"
  - Blogg: "journal"
  - Om mig: "about"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000

# Plugins
plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
# permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
# gems: 
#  - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/writing/"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
